<a href="https://colab.research.google.com/github/gachet/ad-1-24/blob/main/pandas/ejer_loc_iloc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicios simples loc-iloc

In [ ]:
import pandas as pd

In [ ]:
from seaborn import load_dataset
df = load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##El método iloc se utiliza en los DataFrames para seleccionar los elementos en base a su ubicación. Su sintaxis es $$data.iloc[<filas>, <columnas>]$$, donde $$<filas> y <columnas>$$ son la posición de las filas y columnas que se desean seleccionar en el orden que aparecen en el objeto. Una notación familiar para los usuarios de Matlab. En un DataFrame cada una de las filas tiene un número que va desde 0 hasta el total de filas menos uno. Siendo iloc el método que permite seleccionar los datos en base a estos números. Lo mismo que aplica a las columnas.

In [ ]:
df.iloc[0] # Primera fila

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [ ]:
 df.iloc[1]
 # Segunda fila

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [ ]:

df.iloc[-1] # Última fila

total_bill     18.78
tip              3.0
sex           Female
smoker            No
day             Thur
time          Dinner
size               2
Name: 243, dtype: object

In [ ]:
df.iloc[:, 0] # Primera columna

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df.iloc[:, 1] # Segunda columna

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
df.iloc[:, -1] # Última columna

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

##Selección múltiple de filas o columnas mediante posición con iloc

In [ ]:
df.iloc[0:5] # Primeras cinco filas

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.iloc[:, 0:5] # Primeras cinco columnas

     total_bill   tip     sex smoker   day
0         16.99  1.01  Female     No   Sun
1         10.34  1.66    Male     No   Sun
2         21.01  3.50    Male     No   Sun
3         23.68  3.31    Male     No   Sun
4         24.59  3.61  Female     No   Sun
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

[244 rows x 5 columns]

In [ ]:
df.iloc[[0,2,1]]  # Primera, tercera y segunda filas

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df.iloc[:, [0,2,1]]  # Primera, tercera y segunda columnas

     total_bill     sex   tip
0         16.99  Female  1.01
1         10.34    Male  1.66
2         21.01    Male  3.50
3         23.68    Male  3.31
4         24.59  Female  3.61
..          ...     ...   ...
239       29.03    Male  5.92
240       27.18  Female  2.00
241       22.67    Male  2.00
242       17.82    Male  1.75
243       18.78  Female  3.00

[244 rows x 3 columns]

##Consideraciones al utilizar iloc
Es importante tener en cuenta que iloc devuelve una Serie Pandas cuando se selecciona una fila y un DataFrame cuando se selecciona varias. En el caso que sea necesario seleccionar un DataFrame con una única columna es necesario pasar una lista con la columna, no un escalar.

Por otro lado, al seleccionar varias filas o columnas con inicio:fin es necesario recordar que los valores irán desde el principio hasta el final menos uno. Por ejemplo, iloc[1:3] solamente seleccionara la segunda y tercera fila, 1 y 3. Teniendo en cuenta además que los índices en Python comienzan en 0, no en 1 como es el caso de R o Matlab.

##Seleccionar filas y columnas en Pandas en base a etiquetas con loc

En el ejemplo importado las filas tienen como etiquete el número de fila. Por lo que el uso de loc parece similar al de iloc para las filas, aunque tiene algunas diferencias. Por ejemplo, si se han seleccionado las filas del 1 al 4 y se carga el resultado en un nuevo DataFrame a la hora de acceder a la fila 1 con loc se tendrá la primera del nuevo objeto mientras que iloc devolverá la segunda. Esto es así porque los índices se conservan, pero no las posiciones.

In [ ]:
df_sub = df.loc[1:5]

In [ ]:
df_sub.loc[1]

total_bill     10.34
tip             1.66
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 1, dtype: object

In [ ]:
df_sub.iloc[1]

total_bill     21.01
tip              3.5
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 2, dtype: object

##En el caso de las columnas se nota más la diferencia ya que se puede acceder a ellas por nombre, tanto sea una como varias

In [ ]:
df.loc[:, 'tip'] # Columna tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
df.loc[:, ['tip', 'sex', 'day']] # Columnas tip, sex y day

      tip     sex   day
0    1.01  Female   Sun
1    1.66    Male   Sun
2    3.50    Male   Sun
3    3.31    Male   Sun
4    3.61  Female   Sun
..    ...     ...   ...
239  5.92    Male   Sat
240  2.00  Female   Sat
241  2.00    Male   Sat
242  1.75    Male   Sat
243  3.00  Female  Thur

[244 rows x 3 columns]

##Seleccionar filas o columnas en base a una condición con loc
Quizás esta sea una de las opciones más interesantes de las vistas, ya que permite seleccionar los datos en un DataFrame en base a ***condiciones lógicas***. Las cuales se pueden obtener a partir de los valores. Por ejemplo, se puede seleccionar fácilmente los registros correspondientes reservas realizadas por hombres

In [ ]:
is_male = df.loc[:, 'sex'] == 'Male'
is_male
is_male.describe()

count      244
unique       2
top       True
freq       157
Name: sex, dtype: object

In [ ]:
f_male = df.loc[is_male]# le estamos pasando una lista True,False,True,True....
f_male

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

##En este ejemplo se puede ver que primero se ha seleccionado la columna sex y comprobado cuando esta tiene el valor Male. Lo que produce un objeto Serie únicamente con valores ***verdaderos o falso***s. Esta serie es la que posteriormente se utiliza para seleccionar los registros que se cargar en el nuevo DataFrame. Los dos pasos aquí vistos se pueden escribir en una única línea.

In [ ]:
df.loc[df.loc[:, 'sex'] == 'Male']

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [ ]:
df[df['sex'] == 'Male'] # mas compacto

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]